### ISSUE TITLE
question: what does this repository does?

### ISSUE THREAD

**Issue by thebestpossible** [angular/cdk-builds#1]
I was browsing the Angular repositories and I found `cdk-builds`, What does `cdk` stands for?

What is this repository about?

**Comment by Splaktar** [comment]
Component Dev Kit. This repository handles the building of the library and publishing to NPM. Issues and PRs should be submitted against the source repository here: https://github.com/angular/material2

Please close this issue. If you have additional questions and want to discuss the CDK, you can do so on the forums here: https://groups.google.com/forum/#!forum/angular-material2
