### ISSUE TITLE
export supportsShadowDom' was not found in '@angular/cdk/platform

### ISSUE THREAD

**Issue by richard457** [angular/cdk-builds#4]
> Expected beahavior:

`Build no error`

> Current Behavior:

`not building`

> Reproduce:

`run tsc -p tsconfig-serve.json in angular project`

**Comment by HenslerSoftware** [comment]
Are you still having this issue?
We are also having the same problem when updating the latest version of @angulr/cdk

**Comment by greenstevester** [comment]
Also having the same problem:
`ERROR in ./node_modules/@angular/material/esm2015/autocomplete.js 465:16-34
"export '_supportsShadowDom' was not found in '@angular/cdk/platform'
`

**Comment by eKirad** [comment]
Same as -> [Issue #17209](https://github.com/angular/components/issues/17209). Just check if the @angular/material and @angular/cdk dependencies match.

**Comment by greenstevester** [comment]
@eKirad - tried that, still no cigar :-(

My @angular/material and @angular/cdk dependencies (below) match but get:

ERROR in ./node_modules/@angular/material/esm2015/autocomplete.js 465:16-34
"export '_supportsShadowDom' was not found in '@angular/cdk/platform'

"dependencies": {
    "@angular/animations": "~8.1.2",
    "@angular/cdk": "^8.1.4",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/material": "^8.1.4",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "purify-ts": "^0.13.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"

**Comment by eKirad** [comment]
Okay. What about updating the @angular/cdk dependency to ^8.2.2?

**Comment by josiah1888** [comment]
@eKirad I just ran into this issue, but upgraded to @angular/cdk@8.2.2 worked for me

**Comment by devversion** [comment]
Closing this issue as this is not the proper place to discuss this. Please open an issue on the components repository if you still experience similar/or other issues :smile: Thanks!
